<?php echo \Hook\Hook\Hook::run('displayTop');?>
<!DOCTYPE html>
<html lang="<?php echo $this->languages[APP_LANG_ID]['lang'];?>">
<head>
<meta charset="utf-8">
<meta name="renderer" content="webkit">
<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
<meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=0">
<link rel="stylesheet" href="/layui/css/layui.css" media="all">
<link rel="stylesheet" href="/style/admin.css" media="all">
<script src="/layui/layui.js"></script>
<?php echo \Hook\Hook\Hook::run('displayHead');?>