<?php require __DIR__.'/../top.phtml';?>
<title><?php echo $this->title;?></title>
<meta name="description" content="<?php echo $this->description;?>" />
<meta name="keywords" content="<?php echo $this->keywords;?>" />
</head>
<body>
<div class="layui-fluid">
    <div class="layadmin-tips">
        <i class="layui-icon" face>&#xe664;</i>
        <div class="layui-text" style="font-size: 20px;">
            <?php echo $this->exception->getMessage();?>
        </div>
    </div>
</div>
<script>
    layui.config({
        base: '/'
    }).extend({
        index: 'lib/index'
    }).use('index');
</script>
<?php require __DIR__.'/../bottom.phtml';?>