<?php require __DIR__.'/../top.phtml';?>
<title><?php echo $this->title;?></title>
<meta name="description" content="<?php echo $this->description;?>" />
<meta name="keywords" content="<?php echo $this->keywords;?>" />
</head>
<body>
<div class="layui-fluid">
    <div class="layadmin-tips">
        <i class="layui-icon" face>&#xe664;</i>
        <div class="layui-text">
            <h1>
                <span class="layui-anim layui-anim-loop layui-anim-">开</span>
                <span class="layui-anim layui-anim-loop layui-anim-rotate">发</span>
                <span class="layui-anim layui-anim-loop layui-anim-">中...</span>
            </h1>
        </div>
    </div>
</div>
<script>
    layui.config({
        base: '/'
    }).extend({
        index: 'lib/index'
    }).use('index');
</script>
<?php require __DIR__.'/../bottom.phtml';?>